apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  volumes:
    - name: kaniko-config
      secret:
        secretName: martin-deploy-2-ghcr
  containers:
    - name: app
      image: gcr.io/kaniko-project/executor:v1.11.0
      args:
        - --destination=ghcr.io/martin-deploy-2/martin-simulator:v5
        - --context=git://github.com/martin-deploy-2/infrastructure.git#refs/heads/main
        - --context-sub-path=simulator
        - --dockerfile=Dockerfile
        - --single-snapshot
      volumeMounts:
        - mountPath: /kaniko/.docker/config.json
          name: kaniko-config
          subPath: .dockerconfigjson
      resources:
        limits:
          cpu: 4000m
          memory: 8192Mi
        requests:
          cpu: 100m
          memory: 128Mi
