apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: martin-deploy-2-ghcr
spec:
  encryptedData:
    .dockerconfigjson: AgCcH2/hQBALbQIxisaiCCcHPx/9C3YXVH/d7cxvSbVTAY4aLLvWKroQfYj0IvDc/UoKOLPEa4yQnnL8eNQWkrD0XggCKZb865tYlG4MDZL52XMdGIz5KDk/KM61uS6C9YGeluiFWCegzNr5lPn7+l18fAbGRXmaVofmUufv0hdVYlbaaM0dFPAoiQ4b2Mm9guO+nOwVm077sW2AT5rbhZwClxHGW4dRIcakS0p0i7Ixb9KpliUbNszJEdciTYT0HOZrb/t5fCJDP06JpfsuWOi3sotxH52we0dwZTKogsawALo+/gvijAZmII2su/PsmNY/WTzp1LHyJgUGwg6cCyeQ8mNni3FPSIbMmMRBaArERmseJgwMje5WQow3NifPtv4DXTU759v22nr7L0jBRKw+J6YaCbnkOZX4Ecsrmya17ldo5jWYXXSz8EpvgMkHJbeXzYHYsVZLAgAPgVYjrxo1oYb2RKXpsne3lmEbiT9JF4G1iy3s8Qgxd173gMpesniH8SXIj9rDqCi1LkQKj4SgAsss6/wOtnqcKVWpmnwTkKwkjEx5IAX2wJP6I8Dtqi1b1Vz1rdB8LjLxGT3Ynchdhs8VMggY6nffDlClTO0c6RtzX8sCTbJuAY/XL4HkL0204VFlxQODkguDosO8xo1pt1ri/f1y2IhrBS2kSRk08V2eiQaoOwQaOwmsxZyo2xw/M1BaKdQDgs9ZqA/r3BnK2KZ6XhqEUgPc8p0oH7jlVcmsQEWbKqlSilFiJ5kita2jg6JXUHzPcZh6VNXGw5OD6yrmvORnnVs4X48g/zO6W63WVcr5zFWWaW3FjxbJ4T1ah0p2fr0LVjqNr9Vkcachr7NH54RAtAU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: martin-deploy-2-ghcr
    type: kubernetes.io/dockerconfigjson

